# QuiZ-1

In [81]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in d:\anaconda\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in d:\anaconda\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in d:\anaconda\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (2.26.0)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\anaconda\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\anaconda\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests) (2021.10.8)

In [82]:
#import beautifulsoup
from bs4 import BeautifulSoup
import requests

In [83]:
#send request to fetch the  data of site
page=requests.get('https://en.wikipedia.org/wiki/Main_Page')
page

In [8]:
#fetching the content of site
bsoup=BeautifulSoup(page.content)

In [9]:
#scraping the title
headers=[]
for i in bsoup.find_all('span',class_="mw-headline"):
    headers.append(i.text)
headers

['Welcome to Wikipedia',
 "From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages']

# QUIZ 2

In [10]:
#send request
page1=requests.get("https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc")

page1

In [11]:
#scraping the content
bsoup=BeautifulSoup(page1.content)

In [12]:
#sraping the movies name
movies_name=[]
for i in bsoup.find_all('h3',class_="lister-item-header"):
    movies_name.append(i.text.replace("\n"," ").split("(")[0])
movies_name

[' 1. The Shawshank Redemption ',
 ' 2. The Godfather ',
 ' 3. The Dark Knight ',
 ' 4. The Lord of the Rings: The Return of the King ',
 " 5. Schindler's List ",
 ' 6. The Godfather Part II ',
 ' 7. 12 Angry Men ',
 ' 8. Pulp Fiction ',
 ' 9. Inception ',
 ' 10. The Lord of the Rings: The Two Towers ',
 ' 11. Fight Club ',
 ' 12. The Lord of the Rings: The Fellowship of the Ring ',
 ' 13. Forrest Gump ',
 ' 14. Il buono, il brutto, il cattivo ',
 ' 15. The Matrix ',
 ' 16. Goodfellas ',
 ' 17. The Empire Strikes Back ',
 " 18. One Flew Over the Cuckoo's Nest ",
 ' 19. Interstellar ',
 ' 20. Cidade de Deus ',
 ' 21. Sen to Chihiro no kamikakushi ',
 ' 22. Saving Private Ryan ',
 ' 23. The Green Mile ',
 ' 24. La vita è bella ',
 ' 25. Se7en ',
 ' 26. Terminator 2: Judgment Day ',
 ' 27. The Silence of the Lambs ',
 ' 28. Star Wars ',
 ' 29. Seppuku ',
 ' 30. Shichinin no samurai ',
 " 31. It's a Wonderful Life ",
 ' 32. Gisaengchung ',
 ' 33. Whiplash ',
 ' 34. The Intouchables ',
 ' 35. The Prestige ',
 ' 36. The Departed ',
 ' 37. The Pianist ',
 ' 38. Gladiator ',
 ' 39. American History X ',
 ' 40. The Usual Suspects ',
 ' 41. Léon ',
 ' 42. The Lion King ',
 ' 43. Nuovo Cinema Paradiso ',
 ' 44. Hotaru no haka ',
 ' 45. Back to the Future ',
 ' 46. Apocalypse Now ',
 ' 47. Alien ',
 ' 48. Once Upon a Time in the West ',
 ' 49. Psycho ',
 ' 50. Rear Window ']

In [13]:
#scraping the year of movies
year=[]
for i in bsoup.find_all('span',class_="lister-item-year text-muted unbold"):
    year.append(i.text.replace("("," ").split(")")[0])
year

[' 1994',
 ' 1972',
 ' 2008',
 ' 2003',
 ' 1993',
 ' 1974',
 ' 1957',
 ' 1994',
 ' 2010',
 ' 2002',
 ' 1999',
 ' 2001',
 ' 1994',
 ' 1966',
 ' 1999',
 ' 1990',
 ' 1980',
 ' 1975',
 ' 2014',
 ' 2002',
 ' 2001',
 ' 1998',
 ' 1999',
 ' 1997',
 ' 1995',
 ' 1991',
 ' 1991',
 ' 1977',
 ' 1962',
 ' 1954',
 ' 1946',
 ' 2019',
 ' 2014',
 ' 2011',
 ' 2006',
 ' 2006',
 ' 2002',
 ' 2000',
 ' 1998',
 ' 1995',
 ' 1994',
 ' 1994',
 ' 1988',
 ' 1988',
 ' 1985',
 ' 1979',
 ' 1979',
 ' 1968',
 ' 1960',
 ' 1954']

In [14]:
#scraping the rating of movies
rating=[]
for i in bsoup.find_all('div',class_="inline-block ratings-imdb-rating"):
    rating.append(i.text.replace("\n"," "))
rating

['  9.3 ',
 '  9.2 ',
 '  9.0 ',
 '  9.0 ',
 '  9.0 ',
 '  9.0 ',
 '  9.0 ',
 '  8.9 ',
 '  8.8 ',
 '  8.8 ',
 '  8.8 ',
 '  8.8 ',
 '  8.8 ',
 '  8.8 ',
 '  8.7 ',
 '  8.7 ',
 '  8.7 ',
 '  8.7 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.6 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ',
 '  8.5 ']

In [15]:
#importing the libraries
import pandas as pd

In [16]:
#for checking the Length
print(len(movies_name),len(year),len(rating))

50 50 50

In [17]:
#to make the data frame
Df= pd.DataFrame({"Name":movies_name,"Year":year,"Rating":rating})

Df

                                                 Name   Year  Rating
0                        1. The Shawshank Redemption    1994    9.3
1                                   2. The Godfather    1972    9.2
2                                 3. The Dark Knight    2008    9.0
3    4. The Lord of the Rings: The Return of the K...   2003    9.0
4                                5. Schindler's List    1993    9.0
5                           6. The Godfather Part II    1974    9.0
6                                    7. 12 Angry Men    1957    9.0
7                                    8. Pulp Fiction    1994    8.9
8                                       9. Inception    2010    8.8
9          10. The Lord of the Rings: The Two Towers    2002    8.8
10                                    11. Fight Club    1999    8.8
11   12. The Lord of the Rings: The Fellowship of ...   2001    8.8
12                                  13. Forrest Gump    1994    8.8
13               14. Il buono, il brutto, il cattivo    1966    8.8
14                                    15. The Matrix    1999    8.7
15                                    16. Goodfellas    1990    8.7
16                       17. The Empire Strikes Back    1980    8.7
17               18. One Flew Over the Cuckoo's Nest    1975    8.7
18                                  19. Interstellar    2014    8.6
19                                20. Cidade de Deus    2002    8.6
20                 21. Sen to Chihiro no kamikakushi    2001    8.6
21                           22. Saving Private Ryan    1998    8.6
22                                23. The Green Mile    1999    8.6
23                               24. La vita è bella    1997    8.6
24                                         25. Se7en    1995    8.6
25                    26. Terminator 2: Judgment Day    1991    8.6
26                      27. The Silence of the Lambs    1991    8.6
27                                     28. Star Wars    1977    8.6
28                                       29. Seppuku    1962    8.6
29                          30. Shichinin no samurai    1954    8.6
30                         31. It's a Wonderful Life    1946    8.6
31                                  32. Gisaengchung    2019    8.5
32                                      33. Whiplash    2014    8.5
33                              34. The Intouchables    2011    8.5
34                                  35. The Prestige    2006    8.5
35                                  36. The Departed    2006    8.5
36                                   37. The Pianist    2002    8.5
37                                     38. Gladiator    2000    8.5
38                            39. American History X    1998    8.5
39                            40. The Usual Suspects    1995    8.5
40                                          41. Léon    1994    8.5
41                                 42. The Lion King    1994    8.5
42                         43. Nuovo Cinema Paradiso    1988    8.5
43                                44. Hotaru no haka    1988    8.5
44                            45. Back to the Future    1985    8.5
45                                46. Apocalypse Now    1979    8.5
46                                         47. Alien    1979    8.5
47                  48. Once Upon a Time in the West    1968    8.5
48                                        49. Psycho    1960    8.5
49                                   50. Rear Window    1954    8.5

# QUIZ-3

In [18]:
page2=requests.get("https://www.imdb.com/india/top-rated-indian-movies/")
page2

In [19]:
bsoup=BeautifulSoup(page2.content)

In [20]:
#scraping the bollywood movies name
movies=[]
for i in bsoup("td",class_="titleColumn"):
    movies.append(i.text.replace("\n"," ").split("(")[0])
movies

['       1.       Ramayana: The Legend of Prince Rama ',
 '       2.       Rocketry: The Nambi Effect ',
 '       3.       Golmaal ',
 '       4.       777 Charlie ',
 '       5.       Nayakan ',
 '       6.       Anbe Sivam ',
 '       7.       Jai Bhim ',
 '       8.       Pariyerum Perumal ',
 '       9.       3 Idiots ',
 '       10.       Manichitrathazhu ',
 '       11.       Apur Sansar ',
 '       12.       #Home ',
 '       13.       Black Friday ',
 '       14.       Kumbalangi Nights ',
 '       15.       Soorarai Pottru ',
 '       16.       Taare Zameen Par ',
 '       17.       C/o Kancharapalem ',
 '       18.       Kireedam ',
 '       19.       Dangal ',
 '       20.       Kaithi ',
 '       21.       Jersey ',
 '       22.       96 ',
 '       23.       Kantara ',
 '       24.       Asuran ',
 '       25.       Natsamrat ',
 '       26.       Thevar Magan ',
 '       27.       Drishyam 2 ',
 '       28.       Visaaranai ',
 '       29.       Thalapathi ',
 '       30.       Pather Panchali ',
 '       31.       Sarpatta Parambarai ',
 '       32.       Sita Ramam ',
 '       33.       Jaane Bhi Do Yaaro ',
 '       34.       Sardar Udham ',
 '       35.       Thani Oruvan ',
 '       36.       Drishyam ',
 '       37.       Aparajito ',
 '       38.       Khosla Ka Ghosla! ',
 '       39.       Vada Chennai ',
 '       40.       Ratsasan ',
 '       41.       Anniyan ',
 '       42.       Chupke Chupke ',
 '       43.       Peranbu ',
 '       44.       Mahanati ',
 '       45.       Gangs of Wasseypur ',
 '       46.       Satya ',
 '       47.       Bangalore Days ',
 '       48.       Premam ',
 '       49.       Agent Sai Srinivasa Athreya ',
 '       50.       Drishyam ',
 '       51.       Devasuram ',
 '       52.       Super Deluxe ',
 '       53.       Bhaag Milkha Bhaag ',
 '       54.       Tumbbad ',
 '       55.       Andhadhun ',
 '       56.       Vikram Vedha ',
 '       57.       Guide ',
 '       58.       Chithram ',
 '       59.       Vikram ',
 '       60.       Kannathil Muthamittal ',
 '       61.       Zindagi Na Milegi Dobara ',
 '       62.       Sairat ',
 '       63.       Shahid ',
 '       64.       Drishyam 2 ',
 '       65.       Aruvi ',
 '       66.       Chhichhore ',
 '       67.       Paan Singh Tomar ',
 '       68.       Iruvar ',
 '       69.       Pyaasa ',
 '       70.       Swades: We, the People ',
 '       71.       Chak De! India ',
 '       72.       Spadikam ',
 '       73.       Munna Bhai M.B.B.S. ',
 '       74.       Uri: The Surgical Strike ',
 '       75.       Mudhalvan ',
 '       76.       Black ',
 '       77.       Jo Jeeta Wohi Sikandar ',
 '       78.       Dhuruvangal Pathinaaru ',
 '       79.       Hera Pheri ',
 '       80.       Lagaan: Once Upon a Time in India ',
 '       81.       Papanasam ',
 '       82.       Pudhu Pettai ',
 '       83.       Queen ',
 '       84.       PK ',
 '       85.       Article 15 ',
 '       86.       Talvar ',
 '       87.       Sarfarosh ',
 '       88.       Mandela ',
 '       89.       OMG: Oh My God! ',
 '       90.       Soodhu Kavvum ',
 '       91.       Sholay ',
 '       92.       Udaan ',
 '       93.       Barfi! ',
 '       94.       The Legend of Bhagat Singh ',
 '       95.       Jigarthanda ',
 '       96.       Kaakkaa Muttai ',
 '       97.       Ustad Hotel ',
 '       98.       Theeran Adhigaaram Ondru ',
 '       99.       Angoor ',
 '       100.       Baahubali 2: The Conclusion ',
 '       101.       Rang De Basanti ',
 '       102.       Kahaani ',
 '       103.       Masaan ',
 '       104.       A Wednesday ',
 '       105.       Dil Chahta Hai ',
 '       106.       Jana Gana Mana ',
 '       107.       Maheshinte Prathikaaram ',
 '       108.       Baasha ',
 '       109.       Shershaah ',
 '       110.       Virumandi ',
 '       111.       Lage Raho Munna Bhai ',
 '       112.       Iqbal ',
 '       113.       Pink ',
 '       114.       Roja ',
 '       115.       Anand ',
 '       116.       Pithamagan ',
 '       117.       Nil Battey Sannata ',
 '       118.       Kaun Pravin Tambe? ',
 '       119.       Lucia ',
 '       120.       Charulata ',
 '       121.       Bajrangi Bhaijaan ',
 '       122.       Omkara ',
 '       123.       Section 375 ',
 '       124.       Oru Vadakkan Veeragatha ',
 '       125.       Bommarillu ',
 '       126.       Alai Payuthey ',
 '       127.       Bombay ',
 '       128.       K.G.F: Chapter 1 ',
 '       129.       Indian ',
 '       130.       Rangasthalam ',
 '       131.       Dilwale Dulhania Le Jayenge ',
 '       132.       Haider ',
 '       133.       Mughal-E-Azam ',
 '       134.       The Great Indian Kitchen ',
 '       135.       Athadu ',
 '       136.       Andaz Apna Apna ',
 '       137.       Special Chabbis ',
 '       138.       Maqbool ',
 '       139.       Vaaranam Aayiram ',
 '       140.       K.G.F: Chapter 2 ',
 '       141.       Gulaal ',
 '       142.       Padayappa ',
 '       143.       Thadam ',
 '       144.       Maanaadu ',
 '       145.       Pelli Choopulu ',
 '       146.       Ulidavaru Kandanthe ',
 '       147.       Deewaar ',
 '       148.       Vaastav: The Reality ',
 '       149.       Company ',
 '       150.       Ugly ',
 '       151.       Badhaai ho ',
 '       152.       Padosan ',
 '       153.       Gully Boy ',
 '       154.       Naduvula Konjam Pakkatha Kaanom ',
 '       155.       Kshanam ',
 '       156.       Evaru ',
 '       157.       Dev.D ',
 '       158.       My Name Is Khan ',
 '       159.       Aadukalam ',
 '       160.       Nayattu ',
 '       161.       Maanagaram ',
 '       162.       Thondimuthalum Dhriksakshiyum ',
 '       163.       Kal Ho Naa Ho ',
 '       164.       Pranchiyettan and the Saint ',
 '       165.       Major ',
 '       166.       Baishe Srabon ',
 '       167.       Take Off ',
 '       168.       Jab We Met ',
 '       169.       Garuda Gamana Vrishabha Vahana ',
 '       170.       Manjhi: The Mountain Man ',
 '       171.       Mukkabaaz ',
 '       172.       Border ',
 '       173.       Ship of Theseus ',
 '       174.       Ayyappanum Koshiyum ',
 '       175.       Super 30 ',
 '       176.       Vedam ',
 '       177.       Dil Bechara ',
 '       178.       Charlie ',
 '       179.       Deiva Thirumagal ',
 '       180.       Android Kunjappan Version 5.25 ',
 '       181.       Bãhubali: The Beginning ',
 '       182.       Arjun Reddy ',
 '       183.       Salaam Bombay! ',
 '       184.       Padman ',
 '       185.       M.S. Dhoni: The Untold Story ',
 '       186.       Karnan ',
 '       187.       Ankhon Dekhi ',
 '       188.       Baby ',
 '       189.       Kirik Party ',
 '       190.       RRR ',
 '       191.       Jalsaghar ',
 '       192.       Vinnaithaandi Varuvaayaa ',
 '       193.       The Tashkent Files ',
 '       194.       Pizza ',
 '       195.       Malik ',
 '       196.       Hindi Medium ',
 '       197.       Lakshya ',
 '       198.       English Vinglish ',
 '       199.       Johnny Gaddaar ',
 '       200.       Dor ',
 '       201.       Airlift ',
 '       202.       Memories ',
 '       203.       Hey Ram ',
 '       204.       Joseph ',
 '       205.       Hridayam ',
 '       206.       Love Today ',
 '       207.       Gangaajal ',
 '       208.       Kaakha..Kaakha: The Police ',
 '       209.       Anjaam Pathiraa ',
 '       210.       Okkadu ',
 '       211.       Pokiri ',
 '       212.       The Lunchbox ',
 '       213.       Vettaiyaadu Vilaiyaadu ',
 '       214.       Ab Tak Chhappan ',
 '       215.       Mumbai Police ',
 '       216.       Thuppakki ',
 '       217.       RangiTaranga ',
 '       218.       Manam ',
 '       219.       Unnaipol Oruvan ',
 '       220.       Angamaly Diaries ',
 '       221.       Vicky Donor ',
 '       222.       Mother India ',
 '       223.       Ghilli ',
 '       224.       Veer-Zaara ',
 '       225.       Oopiri ',
 '       226.       Secret Superstar ',
 '       227.       Mr. India ',
 '       228.       Stanley Ka Dabba ',
 '       229.       Nayak: The Real Hero ',
 '       230.       Rock On!! ',
 '       231.       Kaththi ',
 '       232.       Mimi ',
 '       233.       Udta Punjab ',
 '       234.       Sonchiriya ',
 '       235.       Badla ',
 '       236.       Thulladha Manamum Thullum ',
 '       237.       Happy Days ',
 '       238.       Dasvidaniya ',
 '       239.       Oru CBI Diary Kurippu ',
 '       240.       Aayirathil Oruvan ',
 '       241.       Raazi ',
 '       242.       Dia ',
 '       243.       Minnal Murali ',
 '       244.       Kai po che! ',
 '       245.       Poove Unakkaga ',
 '       246.       Goodachari ',
 '       247.       Don ',
 '       248.       Joji ',
 '       249.       Aligarh ',
 '       250.       Ko ']

In [21]:
#scraping the year of movies 
Year=[]
for i in bsoup("span",class_="secondaryInfo"):
    Year.append(i.text.replace("("," ").split(")")[0])
Year

[' 1993',
 ' 2022',
 ' 1979',
 ' 2022',
 ' 1987',
 ' 2003',
 ' 2021',
 ' 2018',
 ' 2009',
 ' 1993',
 ' 1959',
 ' 2021',
 ' 2004',
 ' 2019',
 ' 2020',
 ' 2007',
 ' 2018',
 ' 1989',
 ' 2016',
 ' 2019',
 ' 2019',
 ' 2018',
 ' 2022',
 ' 2019',
 ' 2016',
 ' 1992',
 ' 2021',
 ' 2015',
 ' 1991',
 ' 1955',
 ' 2021',
 ' 2022',
 ' 1983',
 ' 2021',
 ' 2015',
 ' 2013',
 ' 1956',
 ' 2006',
 ' 2018',
 ' 2018',
 ' 2005',
 ' 1975',
 ' 2018',
 ' 2018',
 ' 2012',
 ' 1998',
 ' 2014',
 ' 2015',
 ' 2019',
 ' 2015',
 ' 1993',
 ' 2019',
 ' 2013',
 ' 2018',
 ' 2018',
 ' 2017',
 ' 1965',
 ' 1988',
 ' 2022',
 ' 2002',
 ' 2011',
 ' 2016',
 ' 2012',
 ' 2022',
 ' 2016',
 ' 2019',
 ' 2012',
 ' 1997',
 ' 1957',
 ' 2004',
 ' 2007',
 ' 1995',
 ' 2003',
 ' 2019',
 ' 1999',
 ' 2005',
 ' 1992',
 ' 2016',
 ' 2000',
 ' 2001',
 ' 2015',
 ' 2006',
 ' 2013',
 ' 2014',
 ' 2019',
 ' 2015',
 ' 1999',
 ' 2021',
 ' 2012',
 ' 2013',
 ' 1975',
 ' 2010',
 ' 2012',
 ' 2002',
 ' 2014',
 ' 2014',
 ' 2012',
 ' 2017',
 ' 1982',
 ' 2017',
 ' 2006',
 ' 2012',
 ' 2015',
 ' 2008',
 ' 2001',
 ' 2022',
 ' 2016',
 ' 1995',
 ' 2021',
 ' 2004',
 ' 2006',
 ' 2005',
 ' 2016',
 ' 1992',
 ' 1971',
 ' 2003',
 ' 2015',
 ' 2022',
 ' 2013',
 ' 1964',
 ' 2015',
 ' 2006',
 ' 2019',
 ' 1989',
 ' 2006',
 ' 2000',
 ' 1995',
 ' 2018',
 ' 1996',
 ' 2018',
 ' 1995',
 ' 2014',
 ' 1960',
 ' 2021',
 ' 2005',
 ' 1994',
 ' 2013',
 ' 2003',
 ' 2008',
 ' 2022',
 ' 2009',
 ' 1999',
 ' 2019',
 ' 2021',
 ' 2016',
 ' 2014',
 ' 1975',
 ' 1999',
 ' 2002',
 ' 2013',
 ' 2018',
 ' 1968',
 ' 2019',
 ' 2012',
 ' 2016',
 ' 2019',
 ' 2009',
 ' 2010',
 ' 2011',
 ' 2021',
 ' 2017',
 ' 2017',
 ' 2003',
 ' 2010',
 ' 2022',
 ' 2011',
 ' 2017',
 ' 2007',
 ' 2021',
 ' 2015',
 ' 2017',
 ' 1997',
 ' 2012',
 ' 2020',
 ' 2019',
 ' 2010',
 ' 2020',
 ' 2015',
 ' 2011',
 ' 2019',
 ' 2015',
 ' 2017',
 ' 1988',
 ' 2018',
 ' 2016',
 ' 2021',
 ' 2013',
 ' 2015',
 ' 2016',
 ' 2022',
 ' 1958',
 ' 2010',
 ' 2019',
 ' 2012',
 ' 2021',
 ' 2017',
 ' 2004',
 ' 2012',
 ' 2007',
 ' 2006',
 ' 2016',
 ' 2013',
 ' 2000',
 ' 2018',
 ' 2022',
 ' 2022',
 ' 2003',
 ' 2003',
 ' 2020',
 ' 2003',
 ' 2006',
 ' 2013',
 ' 2006',
 ' 2004',
 ' 2013',
 ' 2012',
 ' 2015',
 ' 2014',
 ' 2009',
 ' 2017',
 ' 2012',
 ' 1957',
 ' 2004',
 ' 2004',
 ' 2016',
 ' 2017',
 ' 1987',
 ' 2011',
 ' 2001',
 ' 2008',
 ' 2014',
 ' 2021',
 ' 2016',
 ' 2019',
 ' 2019',
 ' 1999',
 ' 2007',
 ' 2008',
 ' 1988',
 ' 2010',
 ' 2018',
 ' 2020',
 ' 2021',
 ' 2013',
 ' 1996',
 ' 2018',
 ' 1978',
 ' 2021',
 ' 2015',
 ' 2011']

In [22]:
#rating of movies name
rating=[]
for i in bsoup("td",class_="ratingColumn imdbRating"):
    rating.append(i.text.replace("\n"," "))
rating

[' 8.5 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.4 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.3 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.2 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.1 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 8.0 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.9 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.8 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.7 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ',
 ' 7.6 ']

In [23]:
#check the length of all above data
print(len(movies),len(Year),len(rating))

250 250 250

In [24]:
#import pandas lirbray
import pandas as pd

In [25]:
#to make the data frame
df=pd.DataFrame({"Movies_name":movies,"Year":Year,"Rating":rating})
df

                                           Movies_name   Year Rating
0           1.       Ramayana: The Legend of Prince...   1993   8.5
1                 2.       Rocketry: The Nambi Effect    2022   8.4
2                                    3.       Golmaal    1979   8.4
3                                4.       777 Charlie    2022   8.4
4                                    5.       Nayakan    1987   8.4
..                                                 ...    ...    ...
245                             246.       Goodachari    2018   7.7
246                                    247.       Don    1978   7.6
247                                   248.       Joji    2021   7.6
248                                249.       Aligarh    2015   7.6
249                                     250.       Ko    2011   7.6

[250 rows x 3 columns]

# Quiz-4

In [26]:
#send request
page4=requests.get("https://presidentofindia.nic.in/former-presidents.htm")
page4

In [27]:
#fetching the data of site.
bsoup=BeautifulSoup(page4.content)

In [28]:
#to scrap the president name 
President=[]
for i in bsoup("div",class_="presidentListing"):
    President.append(i.text.replace("\n"," ").split("(")[0])
President

[' Shri Ram Nath Kovind ',
 ' Shri Pranab Mukherjee ',
 ' Smt Pratibha Devisingh Patil ',
 ' DR. A.P.J. Abdul Kalam ',
 ' Shri K. R. Narayanan ',
 ' Dr Shankar Dayal Sharma ',
 ' Shri R Venkataraman ',
 ' Giani Zail Singh ',
 ' Shri Neelam Sanjiva Reddy ',
 ' Dr. Fakhruddin Ali Ahmed ',
 ' Shri Varahagiri Venkata Giri ',
 ' Dr. Zakir Husain ',
 ' Dr. Sarvepalli Radhakrishnan ',
 ' Dr. Rajendra Prasad ']

In [29]:
President=[]
for i in bsoup("div",class_="presidentListing"):
    President.append(i.text.replace("\n"," ").split("\n")[0])
President

[' Shri Ram Nath Kovind (birth - 1945) Term of Office: 25 July, 2017 to 25 July, 2022  https://ramnathkovind.nic.in ',
 ' Shri Pranab Mukherjee (1935-2020) Term of Office: 25 July, 2012 to 25 July, 2017  http://pranabmukherjee.nic.in ',
 ' Smt Pratibha Devisingh Patil (birth - 1934) Term of Office: 25 July, 2007 to 25 July, 2012  http://pratibhapatil.nic.in ',
 ' DR. A.P.J. Abdul Kalam (1931-2015) Term of Office: 25 July, 2002 to 25 July, 2007  http://abdulkalam.nic.in ',
 ' Shri K. R. Narayanan (1920 - 2005) Term of Office: 25 July, 1997 to 25 July, 2002  ',
 ' Dr Shankar Dayal Sharma (1918-1999) Term of Office: 25 July, 1992 to 25 July, 1997  ',
 ' Shri R Venkataraman (1910-2009) Term of Office: 25 July, 1987 to 25 July, 1992  ',
 ' Giani Zail Singh (1916-1994) Term of Office: 25 July, 1982 to 25 July, 1987  ',
 ' Shri Neelam Sanjiva Reddy (1913-1996) Term of Office: 25 July, 1977 to 25 July, 1982  ',
 ' Dr. Fakhruddin Ali Ahmed (1905-1977) Term of Office: 24 August, 1974 to 11 February, 1977 ',
 ' Shri Varahagiri Venkata Giri (1894-1980) Term of Office: 3 May, 1969 to 20 July, 1969 and 24 August, 1969 to 24 August, 1974 ',
 ' Dr. Zakir Husain (1897-1969) Term of Office: 13 May, 1967 to 3 May, 1969 ',
 ' Dr. Sarvepalli Radhakrishnan (1888-1975) Term of Office: 13 May, 1962 to 13 May, 1967 ',
 ' Dr. Rajendra Prasad (1884-1963)  Term of Office: 26 January, 1950 to 13 May, 1962 ']

# Q-5  unsolved

In [89]:

#to send the request for scraping the data
Page=requests.get("https://www.icc-cricket.com/rankings/mens/team-rankings/odi")
Page

In [90]:
#fetch the data for scraping
Cr=BeautifulSoup(Page.content)

In [115]:
#to scrap the Odi team match datamatches=[]
odi_team_m=[]
for i in Cr.find_all("table",class_="table"):
    
    odi_team_m.append(i.text.replace("\n"," "))
odi_team_m

['   Pos  Team T   Matches M   Points P   Rating R      1   New Zealand NZ  23 2,670                              116                                  2   England ENG  30 3,400 113   3   Australia AUS  32 3,572 112   4   India IND  36 3,908 109   5   Pakistan PAK  22 2,354 107   6   South Africa SA  24 2,392 100   7   Bangladesh BAN  31 2,913 94   8   Sri Lanka SL  31 2,800 90   9   Afghanistan AFG  20 1,419 71   10   West Indies WI  41 2,902 71   11   Ireland IRE  23 1,214 53   12   Scotland SCO  30 1,392 46   13   Zimbabwe ZIM  26 1,098 42   14   Namibia NAM  25 903 36   15   Netherlands NED  21 673 32   16   Oman OMA  30 919 31   17   UAE UAE  25 693 28   18   United States USA  31 821 26   19   Nepal NEP  26 474 18   20   Papua New Guinea PNG  30 128 4   ']

In [120]:
Page=requests.get("https://www.icc-cricket.com/rankings/mens/player-rankings/odi")
Page

In [121]:
Cr=BeautifulSoup(Page.content)

In [122]:
matches=[]
for i in Cr.find_all("div",class_="rankings-block__top-player"):
    matches.append(i.text)
matches

['\n\n\n\n                                1\n                            \n\n\n(0)\n\n\n\n\nBabar Azam\n\n\nPAK\n                            890\n\n\n\n\n\n',
 '\n\n\n\n                                1\n                            \n\n\n(0)\n\n\n\n\nTrent Boult\n\n\nNZ\n                            752\n\n\n\n\n\n',
 '\n\n\n\n                                1\n                            \n\n\n(0)\n\n\n\n\nShakib Al Hasan\n\n\nBAN\n                            389\n\n\n\n\n\n',
 '\n\n\n\n                                1\n                            \n\n\n(0)\n\n\n\n\nBabar Azam\n\n\nPAK\n                            890\n\n\n\n\n\n',
 '\n\n\n\n                                1\n                            \n\n\n(0)\n\n\n\n\nTrent Boult\n\n\nNZ\n                            752\n\n\n\n\n\n',
 '\n\n\n\n                                1\n                            \n\n\n(0)\n\n\n\n\nShakib Al Hasan\n\n\nBAN\n                            389\n\n\n\n\n\n']

# Q-7

In [123]:
#request from site to scrap
page=requests.get("https://www.cnbc.com/world/?region=world")

page

In [153]:
cnbc=BeautifulSoup(page.content)

In [124]:
##fetching the data headlines
News_soup=BeautifulSoup(requests.get("https://www.cnbc.com/world/?region=world").content,"html.parser")

Headline=[i.text for i in News_soup.find_all(class_="LatestNews-headline") ]
Headline

["Tesla Mega packs, Japan's biggest hydrogen tank: Panasonic tests climate factory",
 'Workers around the world say this is the best U.S. city for expats',
 '3 women on WFH, RTO and trying to find the perfect work-life balance',
 'From Disney to Target to Boeing, retirement is a thing of the past for CEOs',
 'What the pro-business tax agenda is chasing in a changing Congress\xa0',
 'What to know as a record 8.7% Social Security cost-of-living adjustment starts',
 'A new ETF combines international and income investing, and both themes are hot',
 "These are Wall Street's 6 favorite highly discounted tech stocks",
 'Strong returns could be scarce in 2023. How to generate income next year',
 "Not just Twitter. LinkedIn has a fake account problem it's trying to fix",
 'Should you buy a gift for your boss and co-workers for the holidays?',
 "A new home energy upgrade that's becoming a climate and financial winner",
 'Tips for adopting a furry pet for people with allergies from an allergist',
 "Billionaire investor Charlie Munger: The world is 'driven by envy,' not 'greed'",
 'Four-day workweek: How shortening the week could change office life',
 'Nearly 25% of U.S. homebuyers want to move — this state is the top destination',
 'Assessing the risk/reward bargain for the market into 2023',
 "Institutions are charging forward in crypto, even in the industry's darkest days",
 'These stocks have major upside for 2023, Bank of America analyst say',
 "Here's how to prepare for a 1099-K for Venmo, PayPal payments — and slash taxes",
 'Electric school buses are giving kids a cleaner, but costlier, ride to class',
 "Cramer's lightning round: Alphabet is not making enough money",
 'Jim Cramer says Costco is a buy, Lululemon is a wait-and-see',
 'Bahamas attorneys file emergency motion in FTX case for access to client information',
 'Supreme Court takes Coinbase appeal over crypto lawsuits',
 'Cramer’s week ahead: Don’t let the Fed’s meeting obscure investing opportunities',
 "Lawmakers accuse big oil companies of 'greenwashing'",
 "Pro Picks: Watch all of Friday's big stock calls on CNBC",
 'Signals from Costco on prices keep us from overreacting to hotter inflation data',
 'Dow has worst week since September as investors look ahead to CPI, Fed meeting']

In [126]:
cnbc=BeautifulSoup(page.content)

In [129]:
#time scraping of headlines
Times=[]
for i in cnbc("span",class_="LatestNews-wrapper"):
    Times.append(i.text)
Times

['39 Min Ago',
 '39 Min Ago',
 '54 Min Ago',
 '54 Min Ago',
 '1 Hour Ago',
 '3 Hours Ago',
 '3 Hours Ago',
 '3 Hours Ago',
 '3 Hours Ago',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 10, 2022',
 'December 9, 2022',
 'December 9, 2022',
 'December 9, 2022',
 'December 9, 2022',
 'December 9, 2022',
 'December 9, 2022',
 'December 9, 2022',
 'December 9, 2022',
 'December 9, 2022']

In [147]:
#news links
news_link=[]
for i in cnbc.find_all("a",class_="LatestNews-headline"):
    news_link.append(i.get("herf"))
news_link

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [151]:
import pandas as pd
df=pd.DataFrame({"Headline":Headline,"Times":Times,"news_link":news_link})
df

,Headline,Times,news_link
0,"Tesla Mega packs, Japan's biggest hydrogen tan...",39 Min Ago,None
1,Workers around the world say this is the best ...,39 Min Ago,None
2,"3 women on WFH, RTO and trying to find the per...",54 Min Ago,None
3,"From Disney to Target to Boeing, retirement is...",54 Min Ago,None
4,What the pro-business tax agenda is chasing in...,1 Hour Ago,None
5,What to know as a record 8.7% Social Security ...,3 Hours Ago,None
6,A new ETF combines international and income in...,3 Hours Ago,None
7,These are Wall Street's 6 favorite highly disc...,3 Hours Ago,None
8,Strong returns could be scarce in 2023. How to...,3 Hours Ago,None
9,Not just Twitter. LinkedIn has a fake account ...,"December 10, 2022",None
10,Should you buy a gift for your boss and co-wor...,"December 10, 2022",None
11,A new home energy upgrade that's becoming a cl...,"December 10, 2022",None
12,Tips for adopting a furry pet for people with ...,"December 10, 2022",None
13,Billionaire investor Charlie Munger: The world...,"December 10, 2022",None
14,Four-day workweek: How shortening the week cou...,"December 10, 2022",None
15,Nearly 25% of U.S. homebuyers want to move — t...,"December 10, 2022",None
16,Assessing the risk/reward bargain for the mark...,"December 10, 2022",None
17,"Institutions are charging forward in crypto, e...","December 10, 2022",None
18,"These stocks have major upside for 2023, Bank ...","December 10, 2022",None
19,"Here's how to prepare for a 1099-K for Venmo, ...","December 10, 2022",None
20,Electric school buses are giving kids a cleane...,"December 10, 2022",None
21,Cramer's lightning round: Alphabet is not maki...,"December 9, 2022",None
22,"Jim Cramer says Costco is a buy, Lululemon is ...","December 9, 2022",None
23,Bahamas attorneys file emergency motion in FTX...,"December 9, 2022",None
24,Supreme Court takes Coinbase appeal over crypt...,"December 9, 2022",None
25,Cramer’s week ahead: Don’t let the Fed’s meeti...,"December 9, 2022",None
26,Lawmakers accuse big oil companies of 'greenwa...,"December 9, 2022",None
27,Pro Picks: Watch all of Friday's big stock cal...,"December 9, 2022",None
28,Signals from Costco on prices keep us from ove...,"December 9, 2022",None
29,Dow has worst week since September as investor...,"December 9, 2022",None

In [ ]:
# Quiz- 8

In [152]:
page=requests.get("https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles")
page

In [154]:
mi=BeautifulSoup(page.content)

In [ ]:
Paper_Title=[]
Authors=[]
Published_Date=[]
Paper_URL=[]

In [160]:
Paper_Title=[]
for i in mi("a",class_="sc-5smygv-0 fIXTHm"):
    Paper_Title.append(i.text)
Paper_Title

['Reward is enough',
 'Making sense of raw input',
 'Law and logic: A review from an argumentation perspective',
 'Creativity and artificial intelligence',
 'Artificial cognition for social human–robot interaction: An implementation',
 'Explanation in artificial intelligence: Insights from the social sciences',
 'Making sense of sensory input',
 'Conflict-based search for optimal multi-agent pathfinding',
 'Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcement learning',
 'The Hanabi challenge: A new frontier for AI research',
 'Evaluating XAI: A comparison of rule-based and example-based explanations',
 'Argumentation in artificial intelligence',
 'Algorithms for computing strategies in two-player simultaneous move games',
 'Multiple object tracking: A literature review',
 'Selection of relevant features and examples in machine learning',
 'A survey of inverse reinforcement learning: Challenges, methods and progress',
 'Explaining individual predictions when features are dependent: More accurate approximations to Shapley values',
 'A review of possible effects of cognitive biases on interpretation of rule-based machine learning models',
 'Integrating social power into the decision-making of cognitive agents',
 "“That's (not) the output I expected!” On the role of end user expectations in creating explanations of AI systems",
 'Explaining black-box classifiers using post-hoc explanations-by-example: The effect of explanations and error-rates in XAI user studies',
 'Algorithm runtime prediction: Methods & evaluation',
 'Wrappers for feature subset selection',
 'Commonsense visual sensemaking for autonomous driving – On generalised neurosymbolic online abduction integrating vision and semantics',
 'Quantum computation, quantum theory and AI']

In [164]:
Authors=[]
for i in mi("span",class_="sc-1w3fpd7-0 dnCnAO"):

    Authors.append(i.text)
Authors

['Silver, David, Singh, Satinder, Precup, Doina, Sutton, Richard S. ',
 'Evans, Richard, Bošnjak, Matko and 5 more',
 'Prakken, Henry, Sartor, Giovanni ',
 'Boden, Margaret A. ',
 'Lemaignan, Séverin, Warnier, Mathieu and 3 more',
 'Miller, Tim ',
 'Evans, Richard, Hernández-Orallo, José and 3 more',
 'Sharon, Guni, Stern, Roni, Felner, Ariel, Sturtevant, Nathan R. ',
 'Sutton, Richard S., Precup, Doina, Singh, Satinder ',
 'Bard, Nolan, Foerster, Jakob N. and 13 more',
 'van der Waa, Jasper, Nieuwburg, Elisabeth, Cremers, Anita, Neerincx, Mark ',
 'Bench-Capon, T.J.M., Dunne, Paul E. ',
 'Bošanský, Branislav, Lisý, Viliam and 3 more',
 'Luo, Wenhan, Xing, Junliang and 4 more',
 'Blum, Avrim L., Langley, Pat ',
 'Arora, Saurabh, Doshi, Prashant ',
 'Aas, Kjersti, Jullum, Martin, Løland, Anders ',
 'Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Johannes ',
 'Pereira, Gonçalo, Prada, Rui, Santos, Pedro A. ',
 'Riveiro, Maria, Thill, Serge ',
 'Kenny, Eoin M., Ford, Courtney, Quinn, Molly, Keane, Mark T. ',
 'Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyton-Brown, Kevin ',
 'Kohavi, Ron, John, George H. ',
 'Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srikrishna ',
 'Ying, Mingsheng ']

In [165]:
Published_Dat=[]
for i in mi.find_all("span",class_="sc-1thf9ly-2 dvggWt"):

    Published_Dat.append(i.text)
Published_Dat

['October 2021',
 'October 2021',
 'October 2015',
 'August 1998',
 'June 2017',
 'February 2019',
 'April 2021',
 'February 2015',
 'August 1999',
 'March 2020',
 'February 2021',
 'October 2007',
 'August 2016',
 'April 2021',
 'December 1997',
 'August 2021',
 'September 2021',
 'June 2021',
 'December 2016',
 'September 2021',
 'May 2021',
 'January 2014',
 'December 1997',
 'October 2021',
 'February 2010']

In [167]:
Paper_URL=[]
for i in mi.find_all("a",class_="sc-5smygv-0 fIXTHm"):

    Paper_URL.append(i.get("href"))
Paper_URL

['https://www.sciencedirect.com/science/article/pii/S0004370221000862',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000722',
 'https://www.sciencedirect.com/science/article/pii/S0004370215000910',
 'https://www.sciencedirect.com/science/article/pii/S0004370298000551',
 'https://www.sciencedirect.com/science/article/pii/S0004370216300790',
 'https://www.sciencedirect.com/science/article/pii/S0004370218305988',
 'https://www.sciencedirect.com/science/article/pii/S0004370220301855',
 'https://www.sciencedirect.com/science/article/pii/S0004370214001386',
 'https://www.sciencedirect.com/science/article/pii/S0004370299000521',
 'https://www.sciencedirect.com/science/article/pii/S0004370219300116',
 'https://www.sciencedirect.com/science/article/pii/S0004370220301533',
 'https://www.sciencedirect.com/science/article/pii/S0004370207000793',
 'https://www.sciencedirect.com/science/article/pii/S0004370216300285',
 'https://www.sciencedirect.com/science/article/pii/S0004370220301958',
 'https://www.sciencedirect.com/science/article/pii/S0004370297000635',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000515',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000539',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000096',
 'https://www.sciencedirect.com/science/article/pii/S0004370216300868',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000588',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000102',
 'https://www.sciencedirect.com/science/article/pii/S0004370213001082',
 'https://www.sciencedirect.com/science/article/pii/S000437029700043X',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000734',
 'https://www.sciencedirect.com/science/article/pii/S0004370209001398']

In [168]:
count=(len(Paper_Title),len(Authors),len(Published_Dat),len(Paper_URL))
count

(25, 25, 25, 25)

In [169]:
df=pd.DataFrame({"Paper_Title":Paper_Title,"Authors":Authors,"Published_Dat":Published_Dat,"Paper_URL":Paper_URL})
df

,Paper_Title,Authors,Published_Dat,Paper_URL
0,Reward is enough,"Silver, David, Singh, Satinder, Precup, Doina,...",October 2021,https://www.sciencedirect.com/science/article/...
1,Making sense of raw input,"Evans, Richard, Bošnjak, Matko and 5 more",October 2021,https://www.sciencedirect.com/science/article/...
2,Law and logic: A review from an argumentation ...,"Prakken, Henry, Sartor, Giovanni",October 2015,https://www.sciencedirect.com/science/article/...
3,Creativity and artificial intelligence,"Boden, Margaret A.",August 1998,https://www.sciencedirect.com/science/article/...
4,Artificial cognition for social human–robot in...,"Lemaignan, Séverin, Warnier, Mathieu and 3 more",June 2017,https://www.sciencedirect.com/science/article/...
5,Explanation in artificial intelligence: Insigh...,"Miller, Tim",February 2019,https://www.sciencedirect.com/science/article/...
6,Making sense of sensory input,"Evans, Richard, Hernández-Orallo, José and 3 more",April 2021,https://www.sciencedirect.com/science/article/...
7,Conflict-based search for optimal multi-agent ...,"Sharon, Guni, Stern, Roni, Felner, Ariel, Stur...",February 2015,https://www.sciencedirect.com/science/article/...
8,Between MDPs and semi-MDPs: A framework for te...,"Sutton, Richard S., Precup, Doina, Singh, Sati...",August 1999,https://www.sciencedirect.com/science/article/...
9,The Hanabi challenge: A new frontier for AI re...,"Bard, Nolan, Foerster, Jakob N. and 13 more",March 2020,https://www.sciencedirect.com/science/article/...
10,Evaluating XAI: A comparison of rule-based and...,"van der Waa, Jasper, Nieuwburg, Elisabeth, Cre...",February 2021,https://www.sciencedirect.com/science/article/...
11,Argumentation in artificial intelligence,"Bench-Capon, T.J.M., Dunne, Paul E.",October 2007,https://www.sciencedirect.com/science/article/...
12,Algorithms for computing strategies in two-pla...,"Bošanský, Branislav, Lisý, Viliam and 3 more",August 2016,https://www.sciencedirect.com/science/article/...
13,Multiple object tracking: A literature review,"Luo, Wenhan, Xing, Junliang and 4 more",April 2021,https://www.sciencedirect.com/science/article/...
14,Selection of relevant features and examples in...,"Blum, Avrim L., Langley, Pat",December 1997,https://www.sciencedirect.com/science/article/...
15,A survey of inverse reinforcement learning: Ch...,"Arora, Saurabh, Doshi, Prashant",August 2021,https://www.sciencedirect.com/science/article/...
16,Explaining individual predictions when feature...,"Aas, Kjersti, Jullum, Martin, Løland, Anders",September 2021,https://www.sciencedirect.com/science/article/...
17,A review of possible effects of cognitive bias...,"Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Joha...",June 2021,https://www.sciencedirect.com/science/article/...
18,Integrating social power into the decision-mak...,"Pereira, Gonçalo, Prada, Rui, Santos, Pedro A.",December 2016,https://www.sciencedirect.com/science/article/...
19,“That's (not) the output I expected!” On the r...,"Riveiro, Maria, Thill, Serge",September 2021,https://www.sciencedirect.com/science/article/...
20,Explaining black-box classifiers using post-ho...,"Kenny, Eoin M., Ford, Courtney, Quinn, Molly, ...",May 2021,https://www.sciencedirect.com/science/article/...
21,Algorithm runtime prediction: Methods & evalua...,"Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyto...",January 2014,https://www.sciencedirect.com/science/article/...
22,Wrappers for feature subset selection,"Kohavi, Ron, John, George H.",December 1997,https://www.sciencedirect.com/science/article/...
23,Commonsense visual sensemaking for autonomous ...,"Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srik...",October 2021,https://www.sciencedirect.com/science/article/...
24,"Quantum computation, quantum theory and AI","Ying, Mingsheng",February 2010,https://www.sciencedirect.com/science/article/...

# Q-9

In [171]:
dineout= requests.get('https://www.dineout.co.in/delhi-restaurants/buffet-special')
dineout

In [172]:
name=BeautifulSoup(dineout.content)

In [173]:
first_name=name.find("div",class_="restnt-info cursor")
first_name

<div class="restnt-info cursor" data-gatype="RestaurantNameClick"><a analytics-action="RestaurantCardClick" analytics-label="86792_Castle Barbeque" class="restnt-name ellipsis" data-w-onclick="sendAnalyticsCommon|w1-restarant" href="/delhi/castle-barbeque-connaught-place-central-delhi-86792">Castle Barbeque</a><div class="restnt-loc ellipsis" data-w-onclick="stopClickPropagation|w1-restarant"><a data-name="Connaught Place" data-type="LocalityClick" href="/delhi-restaurants/central-delhi/connaught-place">Connaught Place</a>, <a data-name="Central Delhi" data-type="AreaClick" href="/delhi-restaurants/central-delhi">Central Delhi</a></div></div>

In [174]:
first_name.text

'Castle BarbequeConnaught Place, Central Delhi'

In [175]:
title=[]
for i in name.find_all("div",class_="restnt-info cursor"):
    title.append(i.text)
title

['Castle BarbequeConnaught Place, Central Delhi',
 'Jungle Jamboree3CS Mall,Lajpat Nagar - 3, South Delhi',
 'Cafe KnoshThe Leela Ambience Convention Hotel,Shahdara, East Delhi',
 'Castle BarbequePacific Mall,Tagore Garden, West Delhi',
 'The Barbeque CompanyGardens Galleria,Sector 38A, Noida',
 'India GrillHilton Garden Inn,Saket, South Delhi',
 'Delhi BarbequeTaurus Sarovar Portico,Mahipalpur, South Delhi',
 'The Monarch - Bar Be Que VillageIndirapuram Habitat Centre,Indirapuram, Ghaziabad',
 'Indian Grill RoomSuncity Business Tower,Golf Course Road, Gurgaon']

In [176]:
loc=name.find("div",class_="restnt-loc ellipsis")
loc

<div class="restnt-loc ellipsis" data-w-onclick="stopClickPropagation|w1-restarant"><a data-name="Connaught Place" data-type="LocalityClick" href="/delhi-restaurants/central-delhi/connaught-place">Connaught Place</a>, <a data-name="Central Delhi" data-type="AreaClick" href="/delhi-restaurants/central-delhi">Central Delhi</a></div>

In [177]:
loc.text

'Connaught Place, Central Delhi'

In [178]:
location= []
for i in name.find_all("div",class_="restnt-loc ellipsis"):
    location.append(i.text)
location

['Connaught Place, Central Delhi',
 '3CS Mall,Lajpat Nagar - 3, South Delhi',
 'The Leela Ambience Convention Hotel,Shahdara, East Delhi',
 'Pacific Mall,Tagore Garden, West Delhi',
 'Gardens Galleria,Sector 38A, Noida',
 'Hilton Garden Inn,Saket, South Delhi',
 'Taurus Sarovar Portico,Mahipalpur, South Delhi',
 'Indirapuram Habitat Centre,Indirapuram, Ghaziabad',
 'Suncity Business Tower,Golf Course Road, Gurgaon']

In [179]:
rating=name.find("div",class_="restnt-rating rating-4")
rating.text

'4.1'

In [180]:
rating_all=[]
for i in name.find_all("div",class_="restnt-rating rating-4"):
    rating_all.append(i.text)
rating_all

['4.1', '3.9', '4.3', '3.9', '4', '3.9', '3.6', '3.8', '4.3']

In [181]:
cuisine=name.find("span",class_="double-line-ellipsis")
cuisine.text

'₹ 2,000 for 2 (approx) | Chinese, North Indian'

In [182]:
cuisine_all=[]
for i in name.find_all("span",class_="double-line-ellipsis"):
    cuisine_all.append(i.text)
cuisine_all

['₹ 2,000 for 2 (approx) | Chinese, North Indian',
 '₹ 1,680 for 2 (approx) | North Indian, Asian, Italian',
 '₹ 3,000 for 2 (approx) | Italian, Continental',
 '₹ 2,000 for 2 (approx) | Chinese, North Indian',
 '₹ 1,700 for 2 (approx) | North Indian, Chinese',
 '₹ 2,400 for 2 (approx) | North Indian, Italian',
 '₹ 1,800 for 2 (approx) | North Indian',
 '₹ 1,900 for 2 (approx) | North Indian',
 '₹ 2,200 for 2 (approx) | North Indian, Mughlai']

In [183]:
image=name.find("img",class_="no-img")
image

<img alt="Castle Barbeque" class="lazy-load-img no-img" data-gatype="RestaurantImageClick" data-src="https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/k/b/p86792-16062953735fbe1f4d3fb7e.jpg?tr=tr:n-medium" data-url="/delhi/castle-barbeque-connaught-place-central-delhi-86792" data-w-onclick="cardClickHandler"/>

In [184]:
images=[]
for i in name.find_all("img",class_="no-img"):
    images.append(i['data-src'])
images

['https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/k/b/p86792-16062953735fbe1f4d3fb7e.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/p/m/p59633-166088382462ff137009010.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/p/m/p406-15438184745c04ccea491bc.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/j/o/p38113-15959192065f1fcb666130c.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/p/k/p79307-16051787755fad1597f2bf9.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/v/t/p2687-1482477169585cce712b90f.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/d/i/p52501-1661855212630de5eceb6d2.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/n/o/p34822-15599107305cfa594a13c24.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/y/f/p549-165000147262590640c0afc.jpg?tr=tr:n-medium']

In [185]:
print(len(title),len(location),len(rating_all),len(cuisine_all),len(images))

9 9 9 9 9

In [186]:
df= pd.DataFrame({"titles":title,"locations":location,"ratings":rating_all,"cuisine":cuisine_all,"images":images})
df

,titles,locations,ratings,cuisine,images
0,"Castle BarbequeConnaught Place, Central Delhi","Connaught Place, Central Delhi",4.1,"₹ 2,000 for 2 (approx) | Chinese, North Indian",https://im1.dineout.co.in/images/uploads/resta...
1,"Jungle Jamboree3CS Mall,Lajpat Nagar - 3, Sout...","3CS Mall,Lajpat Nagar - 3, South Delhi",3.9,"₹ 1,680 for 2 (approx) | North Indian, Asian, ...",https://im1.dineout.co.in/images/uploads/resta...
2,"Cafe KnoshThe Leela Ambience Convention Hotel,...","The Leela Ambience Convention Hotel,Shahdara, ...",4.3,"₹ 3,000 for 2 (approx) | Italian, Continental",https://im1.dineout.co.in/images/uploads/resta...
3,"Castle BarbequePacific Mall,Tagore Garden, Wes...","Pacific Mall,Tagore Garden, West Delhi",3.9,"₹ 2,000 for 2 (approx) | Chinese, North Indian",https://im1.dineout.co.in/images/uploads/resta...
4,"The Barbeque CompanyGardens Galleria,Sector 38...","Gardens Galleria,Sector 38A, Noida",4,"₹ 1,700 for 2 (approx) | North Indian, Chinese",https://im1.dineout.co.in/images/uploads/resta...
5,"India GrillHilton Garden Inn,Saket, South Delhi","Hilton Garden Inn,Saket, South Delhi",3.9,"₹ 2,400 for 2 (approx) | North Indian, Italian",https://im1.dineout.co.in/images/uploads/resta...
6,"Delhi BarbequeTaurus Sarovar Portico,Mahipalpu...","Taurus Sarovar Portico,Mahipalpur, South Delhi",3.6,"₹ 1,800 for 2 (approx) | North Indian",https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que VillageIndirapuram Ha...,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad",3.8,"₹ 1,900 for 2 (approx) | North Indian",https://im1.dineout.co.in/images/uploads/resta...
8,"Indian Grill RoomSuncity Business Tower,Golf C...","Suncity Business Tower,Golf Course Road, Gurgaon",4.3,"₹ 2,200 for 2 (approx) | North Indian, Mughlai",https://im1.dineout.co.in/images/uploads/resta...

# Q-10

In [195]:
#why did we get here 429 ????
scholar=requests.get("https://scholar.google.com/citations?view_op=top_venues&hl=en")
scholar

In [196]:
soup=BeautifulSoup(scholar.content)

In [198]:
rank=[]
for i in soup.find_all("table",class_="gsc_mp_table"):
#for i in soup.find_all("div",class_="gsc_mvt_table_wrapper"):
    rank.append(i.text)
rank

[]

In [191]:
publication=[]
for i in soup.find_all("td",class_="gsc_mvt_t"):
    publication.append(i.text)
publication

[]

In [192]:
index=[]
for i in soup.find_all("td",class_="gsc_mvt_n"):
    index.append(i.text)
index

[]

In [ ]:
median=[]
for i in soup.find_all("td",class_="gsc_mvt_n"):
    median.append(i.text)
median